/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jbpmn.spec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.netbeans.modeler.core.NBModelerUtil;

/**
 * <p>
 * Java class for tFormalExpression complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * <complexType name="tFormalExpression">
 *   <complexContent>
 *     <extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression">
 *       <attribute name="language" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       <attribute name="evaluatesToTypeRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       <anyAttribute processContents='lax' namespace='##other'/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * </pre>
 *
 *
 */
//@XmlRootElement(name = "formalExpression")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tFormalExpression", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL")
public class TFormalExpression
        extends TExpression {

    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String language;
    @XmlAttribute
    protected String evaluatesToTypeRef;//QName evaluatesToTypeRef;

    /**
     * Gets the value of the language property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the evaluatesToTypeRef property.
     *
     * @return possible object is {@link QName }
     *
     */
    public String getEvaluatesToTypeRef() {
        return evaluatesToTypeRef;
    }

    /**
     * Sets the value of the evaluatesToTypeRef property.
     *
     * @param value allowed object is {@link QName }
     *
     */
    public void setEvaluatesToTypeRef(String value) {
        this.evaluatesToTypeRef = value;
    }

    public static TFormalExpression getNewInstance() {
        TFormalExpression exp = new TFormalExpression();
        exp.setId(NBModelerUtil.getAutoGeneratedStringId());
        return exp;
    }

}
