/** Copyright [2014] Gaurav Gupta
   *
   *Licensed under the Apache License, Version 2.0 (the "License");
   *you may not use this file except in compliance with the License.
   *You may obtain a copy of the License at
   *
   *    http://www.apache.org/licenses/LICENSE-2.0
   *
   *Unless required by applicable law or agreed to in writing, software
   *distributed under the License is distributed on an "AS IS" BASIS,
   *WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   *See the License for the specific language governing permissions and
   *limitations under the License.
   */
 package org.netbeans.jbpmn.spec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.netbeans.modeler.core.NBModelerUtil;


/**
 * <p>Java class for tTimerEventDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="tTimerEventDefinition">
 *   <complexContent>
 *     <extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tEventDefinition">
 *       <choice>
 *         <element name="timeDate" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/>
 *         <element name="timeDuration" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/>
 *         <element name="timeCycle" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/>
 *       </choice>
 *       <anyAttribute processContents='lax' namespace='##other'/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTimerEventDefinition", propOrder = {
    "timeDate",
    "timeDuration",
    "timeCycle"
})
@XmlRootElement(name="timerEventDefinition")
public class TTimerEventDefinition
    extends TEventDefinition
{

    
    
//             <timerEventDefinition id="sid-9664a576-0348-4f66-908a-85538081bce4">
//            <timeDate id="sid-deb0e3ae-0912-4601-a7e1-2addcf259feb" xsi:type="tFormalExpression">123213adasdad</timeDate>
//            <timeCycle id="sid-9dc915e7-f878-456b-a928-ff8ebecce468" xsi:type="tFormalExpression">1231adsa</timeCycle>
//            <timeDuration id="sid-3e8a75be-8798-49f6-b84e-26ca731e0001" xsi:type="tFormalExpression">wq2132</timeDuration>
//         </timerEventDefinition>
    protected TExpression timeDate;
    protected TExpression timeDuration;
    protected TExpression timeCycle;
    
    

    /**
     * Gets the value of the timeDate property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    public TExpression getTimeDate() {
        return timeDate;
    }

    /**
     * Sets the value of the timeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    public void setTimeDate(TExpression value) {
        this.timeDate = value;
    }

    /**
     * Gets the value of the timeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    public TExpression getTimeDuration() {
        return timeDuration;
    }

    /**
     * Sets the value of the timeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    public void setTimeDuration(TExpression value) {
        this.timeDuration = value;
    }

    /**
     * Gets the value of the timeCycle property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    public TExpression getTimeCycle() {
        return timeCycle;
    }

    /**
     * Sets the value of the timeCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    public void setTimeCycle(TExpression value) {
        this.timeCycle = value;
    }

    
    
    
    /* ------------ PROXY  -------------- */
    
    
    
    
    
    
    
    /**
     * @return the timeDateEmbedded
     */
    public String getTimeDateEmbedded() {
        if (this.getTimeDate() != null) {
            return this.getTimeDate().getContent();
        } else {
            return "";
        }
    }

    /**
     * @param timeDateEmbedded the timeDateEmbedded to set
     */
    public void setTimeDateEmbedded(String timeDateEmbedded) {
        if(this.getTimeDate() == null){
         timeDate = new TExpression();
        }
        timeDate.setId(NBModelerUtil.getAutoGeneratedStringId());
        timeDate.setContent(timeDateEmbedded);
    }

    /**
     * @return the timeDurationEmbedded
     */
    public String getTimeDurationEmbedded() {
       if (this.getTimeDuration() != null) {
            return this.getTimeDuration().getContent();
        } else {
            return "";
        }
    }

    /**
     * @param timeDurationEmbedded the timeDurationEmbedded to set
     */
    public void setTimeDurationEmbedded(String timeDurationEmbedded) {
       if(this.getTimeDuration() == null){
         timeDuration = new TExpression();
        }
        timeDuration.setId(NBModelerUtil.getAutoGeneratedStringId());
        timeDuration.setContent(timeDurationEmbedded);
    }

    /**
     * @return the timeCycleEmbedded
     */
    public String getTimeCycleEmbedded() {
       if (this.getTimeCycle() != null) {
            return this.getTimeCycle().getContent();
        } else {
            return "";
        }
    }

    /**
     * @param timeCycleEmbedded the timeCycleEmbedded to set
     */
    public void setTimeCycleEmbedded(String timeCycleEmbedded) {
          if(this.getTimeCycle() == null){
         timeCycle = new TExpression();
        }
        timeCycle.setId(NBModelerUtil.getAutoGeneratedStringId());
        timeCycle.setContent(timeCycleEmbedded);
    }

}
