/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jbpmn.modeler.widget.properties.bpmn.expression;

import javax.swing.JOptionPane;
import org.netbeans.jbpmn.modeler.specification.bpmn.util.BPMNModelUtil;
import org.netbeans.jbpmn.modeler.widget.properties.itemdefinition.ItemDefinitionPanel;
import org.netbeans.jbpmn.spec.TDefinitions;
import org.netbeans.jbpmn.spec.TFormalExpression;
import org.netbeans.jbpmn.spec.TItemDefinition;
import org.netbeans.jbpmn.spec.extend.LanguageManager;
import org.netbeans.modeler.core.ModelerFile;
import org.netbeans.modeler.properties.embedded.GenericEmbeddedEditor;
import org.netbeans.modeler.properties.entity.custom.editor.combobox.client.entity.ComboBoxValue;
import org.netbeans.modeler.properties.entity.custom.editor.combobox.internal.EntityComponent;

public class ExpressionPanel extends GenericEmbeddedEditor<TFormalExpression> {

    private ModelerFile modelerFile;
    private TDefinitions definition;
    private String actionPanelType;
    private TFormalExpression expression;

    public ExpressionPanel(ModelerFile file) {
        this.modelerFile = file;
        definition = (TDefinitions) file.getDefinitionElement();
        initComponents();

        language_ComboBox.setEditable(true);

    }

    void initDataType() {
        evaluatesToType_ComboBox.removeAllItems();
        for (ComboBoxValue<TItemDefinition> itemDefinition : BPMNModelUtil.getItemDefinitionList(modelerFile)) {
            evaluatesToType_ComboBox.addItem(itemDefinition);
        }
    }

    @Override
    public void init() {
    }

    @Override
    public TFormalExpression getValue() {
        if (expression == null) {
            expression = TFormalExpression.getNewInstance();
        }
        BPMNModelUtil.setExpressionPanelValue(expression, language_ComboBox, script_TextArea, evaluatesToType_ComboBox);
        if (expression.isEmpty()) {
            expression = null;
        }
        return expression;
    }

    @Override
    public void setValue(TFormalExpression expression) {
        this.expression = expression;
        initScriptTypeComboBox();
        initDataType();
        BPMNModelUtil.initExpressionPanel(expression, language_ComboBox, script_TextArea, evaluatesToType_ComboBox);
    }

    private void initScriptTypeComboBox() {
        language_ComboBox.removeAllItems();
        for (ComboBoxValue<String> language : LanguageManager.getLanguageList()) {
            language_ComboBox.addItem(language);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setting_PopupMenu = new javax.swing.JPopupMenu();
        createItem_MenuItem = new javax.swing.JMenuItem();
        editItem_MenuItem = new javax.swing.JMenuItem();
        deleteItem_MenuItem = new javax.swing.JMenuItem();
        expression_LayeredPane = new javax.swing.JLayeredPane();
        language_LayeredPane = new javax.swing.JLayeredPane();
        language_Label = new javax.swing.JLabel();
        language_ComboBox = new javax.swing.JComboBox();
        script_LayeredPane = new javax.swing.JLayeredPane();
        script_Label = new javax.swing.JLabel();
        script_ScrollPane = new javax.swing.JScrollPane();
        script_TextArea = new javax.swing.JTextArea();
        evaluateType_LayeredPane = new javax.swing.JLayeredPane();
        evaluatesToType_Label = new javax.swing.JLabel();
        evaluatesToType_ComboBox = new javax.swing.JComboBox();
        evaluatesToType_Action = new javax.swing.JButton();

        createItem_MenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/jbpmn/modeler/widget/properties/resource/icon_plus.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(createItem_MenuItem, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.createItem_MenuItem.text_1")); // NOI18N
        createItem_MenuItem.setToolTipText(org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.createItem_MenuItem.toolTipText_1")); // NOI18N
        createItem_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createItem_MenuItemActionPerformed(evt);
            }
        });
        setting_PopupMenu.add(createItem_MenuItem);

        editItem_MenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/jbpmn/modeler/widget/properties/resource/edit.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(editItem_MenuItem, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.editItem_MenuItem.text_1")); // NOI18N
        editItem_MenuItem.setToolTipText(org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.editItem_MenuItem.toolTipText_1")); // NOI18N
        editItem_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItem_MenuItemActionPerformed(evt);
            }
        });
        setting_PopupMenu.add(editItem_MenuItem);

        deleteItem_MenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/jbpmn/modeler/widget/properties/resource/delete.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteItem_MenuItem, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.deleteItem_MenuItem.text_1")); // NOI18N
        deleteItem_MenuItem.setToolTipText(org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.deleteItem_MenuItem.toolTipText_1")); // NOI18N
        deleteItem_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItem_MenuItemActionPerformed(evt);
            }
        });
        setting_PopupMenu.add(deleteItem_MenuItem);

        org.openide.awt.Mnemonics.setLocalizedText(language_Label, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.language_Label.text_1")); // NOI18N
        language_Label.setToolTipText(org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.language_Label.toolTipText_1")); // NOI18N

        javax.swing.GroupLayout language_LayeredPaneLayout = new javax.swing.GroupLayout(language_LayeredPane);
        language_LayeredPane.setLayout(language_LayeredPaneLayout);
        language_LayeredPaneLayout.setHorizontalGroup(
            language_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(language_LayeredPaneLayout.createSequentialGroup()
                .addComponent(language_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(language_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        language_LayeredPaneLayout.setVerticalGroup(
            language_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(language_LayeredPaneLayout.createSequentialGroup()
                .addGroup(language_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(language_Label)
                    .addComponent(language_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        language_LayeredPane.setLayer(language_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        language_LayeredPane.setLayer(language_ComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(script_Label, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.script_Label.text_1")); // NOI18N
        script_Label.setToolTipText(org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.script_Label.toolTipText_1")); // NOI18N

        script_TextArea.setColumns(20);
        script_TextArea.setRows(5);
        script_ScrollPane.setViewportView(script_TextArea);

        javax.swing.GroupLayout script_LayeredPaneLayout = new javax.swing.GroupLayout(script_LayeredPane);
        script_LayeredPane.setLayout(script_LayeredPaneLayout);
        script_LayeredPaneLayout.setHorizontalGroup(
            script_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(script_LayeredPaneLayout.createSequentialGroup()
                .addComponent(script_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(script_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );
        script_LayeredPaneLayout.setVerticalGroup(
            script_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(script_LayeredPaneLayout.createSequentialGroup()
                .addComponent(script_Label)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(script_LayeredPaneLayout.createSequentialGroup()
                .addComponent(script_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        script_LayeredPane.setLayer(script_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        script_LayeredPane.setLayer(script_ScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(evaluatesToType_Label, org.openide.util.NbBundle.getMessage(ExpressionPanel.class, "ExpressionPanel.evaluatesToType_Label.text_1")); // NOI18N

        evaluatesToType_Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/jbpmn/modeler/widget/properties/operation/settings.png"))); // NOI18N
        evaluatesToType_Action.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                evaluatesToType_ActionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout evaluateType_LayeredPaneLayout = new javax.swing.GroupLayout(evaluateType_LayeredPane);
        evaluateType_LayeredPane.setLayout(evaluateType_LayeredPaneLayout);
        evaluateType_LayeredPaneLayout.setHorizontalGroup(
            evaluateType_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluateType_LayeredPaneLayout.createSequentialGroup()
                .addComponent(evaluatesToType_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluatesToType_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluatesToType_Action, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        evaluateType_LayeredPaneLayout.setVerticalGroup(
            evaluateType_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluateType_LayeredPaneLayout.createSequentialGroup()
                .addGroup(evaluateType_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evaluateType_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(evaluatesToType_Label)
                        .addComponent(evaluatesToType_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(evaluatesToType_Action))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        evaluateType_LayeredPane.setLayer(evaluatesToType_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        evaluateType_LayeredPane.setLayer(evaluatesToType_ComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        evaluateType_LayeredPane.setLayer(evaluatesToType_Action, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout expression_LayeredPaneLayout = new javax.swing.GroupLayout(expression_LayeredPane);
        expression_LayeredPane.setLayout(expression_LayeredPaneLayout);
        expression_LayeredPaneLayout.setHorizontalGroup(
            expression_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expression_LayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evaluateType_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(expression_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(expression_LayeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(expression_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(script_LayeredPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(language_LayeredPane, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
        expression_LayeredPaneLayout.setVerticalGroup(
            expression_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expression_LayeredPaneLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(evaluateType_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(expression_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(expression_LayeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(language_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(script_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        expression_LayeredPane.setLayer(language_LayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        expression_LayeredPane.setLayer(script_LayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        expression_LayeredPane.setLayer(evaluateType_LayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expression_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expression_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void evaluatesToType_ActionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluatesToType_ActionMousePressed
        actionPanelType = "evaluatesToType";
        setting_PopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_evaluatesToType_ActionMousePressed

    EntityComponent getActionPanel() {
        if ("evaluatesToType".equals(actionPanelType)) {
            return new ItemDefinitionPanel(modelerFile);
        } else {
            return null;
        }
    }

    ComboBoxValue getSelectedActionItem() {
        if ("evaluatesToType".equals(actionPanelType)) {
            return (ComboBoxValue) evaluatesToType_ComboBox.getSelectedItem();
        } else {
            return null;
        }
    }
    private void createItem_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createItem_MenuItemActionPerformed
        EntityComponent itemComponent = getActionPanel();// actionHandler.getItemPanel();

        itemComponent.init();
        itemComponent.createEntity(ComboBoxValue.class);
        itemComponent.setVisible(true);

        if (itemComponent.getDialogResult() == javax.swing.JOptionPane.OK_OPTION) {
            ComboBoxValue comboBoxValue = (ComboBoxValue) itemComponent.getEntity();

            if ("evaluatesToType".equals(actionPanelType)) {
                evaluatesToType_ComboBox.addItem(comboBoxValue);
                evaluatesToType_ComboBox.setSelectedItem(comboBoxValue);
                definition.addItemDefinition((TItemDefinition) comboBoxValue.getValue());
            }

        }
    }//GEN-LAST:event_createItem_MenuItemActionPerformed

    private void editItem_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItem_MenuItemActionPerformed
        ComboBoxValue comboBoxValue;
        try {
            comboBoxValue = getSelectedActionItem();// = (ComboBoxValue) interface_ComboBox.getSelectedItem();

            if (comboBoxValue == null) {
                JOptionPane.showMessageDialog(null, "No element selected !", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            EntityComponent itemComponent = getActionPanel();
            itemComponent.init();
            itemComponent.updateEntity(comboBoxValue);
            itemComponent.setVisible(true);
        } catch (IllegalStateException ex) {
            System.out.println("EX : " + ex.toString());
        }
    }//GEN-LAST:event_editItem_MenuItemActionPerformed

    private void deleteItem_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItem_MenuItemActionPerformed
        ComboBoxValue comboBoxValue;
        try {
            comboBoxValue = getSelectedActionItem();// = (ComboBoxValue) interface_ComboBox.getSelectedItem();

            if (comboBoxValue == null) {
                JOptionPane.showMessageDialog(null, "No element selected !", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if ("evaluatesToType".equals(actionPanelType)) {
                int option = JOptionPane.showConfirmDialog(null, "Are you sue you want to delete this Data Type ?", "Delete Data Type", JOptionPane.OK_CANCEL_OPTION);
                if (option == JOptionPane.OK_OPTION) {
                    definition.removeRootElement((TItemDefinition) comboBoxValue.getValue());
                    evaluatesToType_ComboBox.removeItem(comboBoxValue);
                }
            }
        } catch (IllegalStateException ex) {
            System.out.println("EX : " + ex.toString());
        }
    }//GEN-LAST:event_deleteItem_MenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createItem_MenuItem;
    private javax.swing.JMenuItem deleteItem_MenuItem;
    private javax.swing.JMenuItem editItem_MenuItem;
    private javax.swing.JLayeredPane evaluateType_LayeredPane;
    private javax.swing.JButton evaluatesToType_Action;
    private javax.swing.JComboBox evaluatesToType_ComboBox;
    protected javax.swing.JLabel evaluatesToType_Label;
    private javax.swing.JLayeredPane expression_LayeredPane;
    private javax.swing.JComboBox language_ComboBox;
    protected javax.swing.JLabel language_Label;
    private javax.swing.JLayeredPane language_LayeredPane;
    protected javax.swing.JLabel script_Label;
    private javax.swing.JLayeredPane script_LayeredPane;
    private javax.swing.JScrollPane script_ScrollPane;
    private javax.swing.JTextArea script_TextArea;
    private javax.swing.JPopupMenu setting_PopupMenu;
    // End of variables declaration//GEN-END:variables
}
