/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jbpmn.modeler.widget.properties.bpmn.loop.attribute;

import org.netbeans.modeler.properties.embedded.GenericEmbeddedEditor;

public class LoopCharacteristicsPanel extends GenericEmbeddedEditor {

    /**
     * Creates new form LoopCharacteristicsPanel
     */
    public LoopCharacteristicsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        looptype_LayeredPane = new javax.swing.JLayeredPane();
        looptype_Label = new javax.swing.JLabel();
        looptype_ComboBox = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(looptype_Label, org.openide.util.NbBundle.getMessage(LoopCharacteristicsPanel.class, "LoopCharacteristicsPanel.looptype_Label.text")); // NOI18N
        looptype_Label.setToolTipText(org.openide.util.NbBundle.getMessage(LoopCharacteristicsPanel.class, "LoopCharacteristicsPanel.looptype_Label.toolTipText")); // NOI18N

        looptype_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Standard", "Multi-Instance Parallel", "Multi-Instance Sequential", " " }));
        looptype_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                looptype_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout looptype_LayeredPaneLayout = new javax.swing.GroupLayout(looptype_LayeredPane);
        looptype_LayeredPane.setLayout(looptype_LayeredPaneLayout);
        looptype_LayeredPaneLayout.setHorizontalGroup(
            looptype_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(looptype_LayeredPaneLayout.createSequentialGroup()
                .addComponent(looptype_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(looptype_ComboBox, 0, 300, Short.MAX_VALUE))
        );
        looptype_LayeredPaneLayout.setVerticalGroup(
            looptype_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(looptype_LayeredPaneLayout.createSequentialGroup()
                .addGroup(looptype_LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(looptype_Label)
                    .addComponent(looptype_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        looptype_LayeredPane.setLayer(looptype_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        looptype_LayeredPane.setLayer(looptype_ComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(looptype_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(looptype_LayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(looptype_LayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void looptype_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_looptype_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_looptype_ComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JComboBox looptype_ComboBox;
    protected javax.swing.JLabel looptype_Label;
    private javax.swing.JLayeredPane looptype_LayeredPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void init() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getValue() {
        return "";
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setValue(Object val) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
