/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jbpmn.modeler.widget.properties.io_specification;

import java.util.List;
import org.netbeans.modeler.properties.nentity.DynamicEntityComponent;
import org.netbeans.modeler.properties.nentity.NAttributeEntity;


 
public class DataDialog extends DynamicEntityComponent {
String originalId;
    /**
     * Creates new form NewJDialog
     */
     public DataDialog(NAttributeEntity attributeEntity) {        
        super(attributeEntity);
        initComponents();
//        this.getRootPane().setDefaultButton(this.jButtonOK);
    }
     
  @Override
    public void createEntity() {
        id_TextField.setText("");
        name_TextField.setText("");
        isCollection_CheckBox.setSelected(Boolean.FALSE);
        itemSubjectRef_TextField.setText("");
    }

    @Override
    public void updateEntity() {
        id_TextField.setText((String) row[0]);
        name_TextField.setText((String) row[1]);
        isCollection_CheckBox.setSelected((Boolean) row[2]);
        itemSubjectRef_TextField.setText((String) row[3]);
        originalId = (String) row[0];
   }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        itemSubjectRef_Label = new javax.swing.JLabel();
        itemSubjectRef_TextField = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        id_Label = new javax.swing.JLabel();
        id_TextField = new javax.swing.JTextField();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        name_Label = new javax.swing.JLabel();
        name_TextField = new javax.swing.JTextField();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        isCollection_Label = new javax.swing.JLabel();
        isCollection_CheckBox = new javax.swing.JCheckBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        save_Button = new javax.swing.JButton();
        cancel_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        org.openide.awt.Mnemonics.setLocalizedText(itemSubjectRef_Label, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.itemSubjectRef_Label.text")); // NOI18N

        itemSubjectRef_TextField.setText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.itemSubjectRef_TextField.text")); // NOI18N
        itemSubjectRef_TextField.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.itemSubjectRef_TextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(itemSubjectRef_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemSubjectRef_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemSubjectRef_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemSubjectRef_Label))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jLayeredPane3.setLayer(itemSubjectRef_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(itemSubjectRef_TextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(id_Label, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.id_Label.text")); // NOI18N

        id_TextField.setText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.id_TextField.text")); // NOI18N
        id_TextField.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.id_TextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_TextField))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_Label))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jLayeredPane4.setLayer(id_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(id_TextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(name_Label, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.name_Label.text")); // NOI18N

        name_TextField.setText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.name_TextField.text")); // NOI18N
        name_TextField.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.name_TextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addComponent(name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_Label))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jLayeredPane5.setLayer(name_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(name_TextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(isCollection_Label, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.isCollection_Label.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(isCollection_CheckBox, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.isCollection_CheckBox.text")); // NOI18N
        isCollection_CheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.isCollection_CheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addComponent(isCollection_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isCollection_CheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCollection_CheckBox)
                    .addComponent(isCollection_Label))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jLayeredPane6.setLayer(isCollection_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(isCollection_CheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(save_Button, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.save_Button.text")); // NOI18N
        save_Button.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.save_Button.toolTipText")); // NOI18N
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancel_Button, org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.cancel_Button.text")); // NOI18N
        cancel_Button.setToolTipText(org.openide.util.NbBundle.getMessage(DataDialog.class, "DataDialog.cancel_Button.toolTipText")); // NOI18N
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_Button)
                .addGap(2, 2, 2))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(save_Button)
                .addComponent(cancel_Button))
        );
        jLayeredPane2.setLayer(save_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cancel_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane5)
                    .addComponent(jLayeredPane6)
                    .addComponent(jLayeredPane3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
          
   //     id is required...
    if (this.id_TextField.getText().trim().length() <= 0 /*|| Pattern.compile("[^\\w-]").matcher(this.id_TextField.getText().trim()).find()*/)
        {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Id can't be empty","Invalid Value",
                    javax.swing.JOptionPane.WARNING_MESSAGE );
            return;
        }//I18n 
    
    if (this.name_TextField.getText().trim().length() <= 0 /*|| Pattern.compile("[^\\w-]").matcher(this.id_TextField.getText().trim()).find()*/)
        {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Name can't be empty","Invalid Value",
                    javax.swing.JOptionPane.WARNING_MESSAGE );
            return;
        }//I18n 
    if (this.itemSubjectRef_TextField.getText().trim().length() <= 0 /*|| Pattern.compile("[^\\w-]").matcher(this.id_TextField.getText().trim()).find()*/)
        {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Item Subject Reference can't be empty","Invalid Value",
                    javax.swing.JOptionPane.WARNING_MESSAGE );
            return;
        }//I18n
        
//         check if the id is unique...
 String id = id_TextField.getText().trim();
            for (Object[] row : (List<Object[]>)this.getAttributeEntity().getTableDataListener().getData())   {
                if (row[0].equals(id) && (originalId == null || !originalId.equals(id))) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                    "Id already in use!","Invalid Value",
                    javax.swing.JOptionPane.WARNING_MESSAGE );
                    return;
                }
            }//I18n

        if(row==null){
        row = new Object[4];
        }
     
        row[0] = id_TextField.getText().trim();
        row[1] = name_TextField.getText().trim();
        row[2] = isCollection_CheckBox.isSelected();
        row[3] = itemSubjectRef_TextField.getText().trim();
        setVisible(false);
        this.setDialogResult( javax.swing.JOptionPane.OK_OPTION);
        dispose();
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        cancelActionPerformed(evt);
    }//GEN-LAST:event_cancel_ButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancel_Button;
    protected javax.swing.JLabel id_Label;
    protected javax.swing.JTextField id_TextField;
    protected javax.swing.JCheckBox isCollection_CheckBox;
    protected javax.swing.JLabel isCollection_Label;
    protected javax.swing.JLabel itemSubjectRef_Label;
    protected javax.swing.JTextField itemSubjectRef_TextField;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    protected javax.swing.JLabel name_Label;
    protected javax.swing.JTextField name_TextField;
    protected javax.swing.JButton save_Button;
    // End of variables declaration//GEN-END:variables

    

 
     
   

   
}
